#!/usr/bin/env sh

display_help() {
	cat <<-EOF
	Usage: $(basename "$0") COMMAND [ARGS...]

	Commands:
	  read		Print a note to STDOUT.
	  write		Create or edit a note.
	  list		List all the notes.
	  move		Rename a note.
	  remove	Delete a note.
	  help		Display the help.
	EOF
}

clean_directory() {
	find . -depth -type d -exec rmdir {} \; 2> /dev/null
}

if [ -z "$CALEPIN_PATH" ]; then
	CALEPIN_PATH="$HOME/.calepin"
fi

if ! [ -d "$CALEPIN_PATH" ]; then
	mkdir -p "$CALEPIN_PATH"
	echo "Create <$CALEPIN_PATH>."
fi

cd "$CALEPIN_PATH" || exit

case $1 in
	read)
		[ -f "./$2" ] && cat "./$2";;
	write)
		mkdir -p "$(dirname "./$2")"
		"$EDITOR" "./$2" && clean_directory;;
	list)
		find . -type f;;
	move)
		if [ -f "./$2" ] && ! [ -f "./$3" ]; then
			mkdir -p "$(dirname "./$3")"
			mv "./$2" "./$3" && clean_directory
		fi;;
	remove)
		[ -e "./$2" ] && rm -rf "./$2" && clean_directory;;
	help)
		display_help;;
	*)
		display_help
		exit 1;;
esac
